-- Países (portafolio real: Colombia, México, España, etc.)
CREATE TABLE av_paises (
    pais_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    codigo_iso   VARCHAR2(3) NOT NULL,   -- ISO 3166-1 alpha-3: COL, MEX, USA
    nombre       VARCHAR2(60) NOT NULL,
    continente   VARCHAR2(20) NOT NULL,
    estado       VARCHAR2(15) DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_av_paises PRIMARY KEY (pais_id),
    CONSTRAINT uq_av_pais_iso UNIQUE (codigo_iso),
    CONSTRAINT uq_av_pais_nombre UNIQUE (nombre),
    CONSTRAINT ck_av_pais_estado CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT ck_av_pais_continente CHECK (continente IN
        ('AMERICA', 'EUROPA', 'ASIA', 'AFRICA', 'OCEANIA', 'ANTARTIDA'))
);

-- Ciudades (cada ciudad pertenece a un país)
CREATE TABLE av_ciudades (
    ciudad_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    pais_id     NUMBER NOT NULL,
    nombre      VARCHAR2(60) NOT NULL,
    estado      VARCHAR2(15) DEFAULT 'ACTIVA' NOT NULL,

    CONSTRAINT pk_av_ciudades PRIMARY KEY (ciudad_id),
    CONSTRAINT fk_av_ciudad_pais FOREIGN KEY (pais_id)
        REFERENCES av_paises (pais_id),
    CONSTRAINT uq_av_ciudad_pais UNIQUE (pais_id, nombre),
    CONSTRAINT ck_av_ciudad_estado CHECK (estado IN ('ACTIVA', 'INACTIVA'))
);

-- Aerolíneas
CREATE TABLE av_aerolineas (
    aerolinea_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    codigo_iata   VARCHAR2(3) NOT NULL,    -- AV (Avianca), LA (Latam), etc.
    nombre        VARCHAR2(60) NOT NULL,
    pais_id       NUMBER NOT NULL,         -- país de origen
    estado        VARCHAR2(15) DEFAULT 'ACTIVA' NOT NULL,

    CONSTRAINT pk_av_aerolineas PRIMARY KEY (aerolinea_id),
    CONSTRAINT fk_av_aero_pais FOREIGN KEY (pais_id)
        REFERENCES av_paises (pais_id),
    CONSTRAINT uq_av_aero_iata UNIQUE (codigo_iata),
    CONSTRAINT ck_av_aero_estado CHECK (estado IN ('ACTIVA', 'INACTIVA'))
);

-- Aeropuertos
CREATE TABLE av_aeropuertos (
    aeropuerto_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    codigo_iata    VARCHAR2(3) NOT NULL,   -- MDE, BOG, JFK
    nombre         VARCHAR2(80) NOT NULL,
    ciudad_id      NUMBER NOT NULL,
    estado         VARCHAR2(15) DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_av_aeropuertos PRIMARY KEY (aeropuerto_id),
    CONSTRAINT fk_av_aerop_ciudad FOREIGN KEY (ciudad_id)
        REFERENCES av_ciudades (ciudad_id),
    CONSTRAINT uq_av_aerop_iata UNIQUE (codigo_iata),
    CONSTRAINT ck_av_aerop_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

--------------------------------------------------- CLIENTES -----------------------------------------------------------------

CREATE TABLE av_clientes (
    cliente_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipo_doc          VARCHAR2(5) NOT NULL,
    num_doc           VARCHAR2(20) NOT NULL,
    nombre            VARCHAR2(40) NOT NULL,
    apellido          VARCHAR2(40) NOT NULL,
    fecha_nacimiento  DATE NOT NULL,
    email             VARCHAR2(60),
    telefono          VARCHAR2(20),
    pais_id           NUMBER NOT NULL,      -- nacionalidad/residencia
    estado            VARCHAR2(15) DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_av_clientes PRIMARY KEY (cliente_id),
    CONSTRAINT fk_av_cli_pais FOREIGN KEY (pais_id)
        REFERENCES av_paises (pais_id),
    CONSTRAINT uq_av_cli_doc UNIQUE (tipo_doc, num_doc),
    CONSTRAINT ck_av_cli_estado CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT ck_av_cli_tipo_doc CHECK (tipo_doc IN ('CC', 'CE', 'TI', 'PAS', 'NIT'))
x);

------------------ INVENTARIO DE SERVICIOS --------------------------------------------
-- Hoteles (un hotel está en una ciudad, y la ciudad ya cuelga de un país)
CREATE TABLE av_hoteles (
    hotel_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre      VARCHAR2(60) NOT NULL,
    ciudad_id   NUMBER NOT NULL,
    direccion   VARCHAR2(120) NOT NULL,
    estrellas   NUMBER(1) NOT NULL,
    estado      VARCHAR2(15) DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_av_hoteles PRIMARY KEY (hotel_id),
    CONSTRAINT fk_av_hot_ciudad FOREIGN KEY (ciudad_id)
        REFERENCES av_ciudades (ciudad_id),
    CONSTRAINT ck_av_hot_estrellas CHECK (estrellas BETWEEN 1 AND 5),
    CONSTRAINT ck_av_hot_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- Habitaciones (cada habitación pertenece a un hotel)
CREATE TABLE av_habitaciones (
    habitacion_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    hotel_id        NUMBER NOT NULL,
    num_habitacion  VARCHAR2(10) NOT NULL,
    tipo            VARCHAR2(20) NOT NULL,
    capacidad       NUMBER(2) NOT NULL,
    precio_noche    NUMBER(10,2) NOT NULL,
    estado          VARCHAR2(15) DEFAULT 'DISPONIBLE' NOT NULL,

    CONSTRAINT pk_av_habitaciones PRIMARY KEY (habitacion_id),
    CONSTRAINT fk_av_hab_hotel FOREIGN KEY (hotel_id)
        REFERENCES av_hoteles (hotel_id),
    CONSTRAINT uq_av_hab_num UNIQUE (hotel_id, num_habitacion),
    CONSTRAINT ck_av_hab_tipo CHECK (tipo IN ('SENCILLA', 'DOBLE', 'SUITE', 'FAMILIAR')),
    CONSTRAINT ck_av_hab_estado CHECK (estado IN ('DISPONIBLE', 'NO DISPONIBLE')),
    CONSTRAINT ck_av_hab_precio CHECK (precio_noche >= 0),
    CONSTRAINT ck_av_hab_cap CHECK (capacidad BETWEEN 1 AND 6)
);

-- Vuelos (oferta del catálogo: ruta, fecha y precio base)
CREATE TABLE av_vuelos (
    vuelo_id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    aerolinea_id          NUMBER NOT NULL,
    num_vuelo             VARCHAR2(10) NOT NULL,    -- AV245, LA830
    aeropuerto_origen_id  NUMBER NOT NULL,
    aeropuerto_destino_id NUMBER NOT NULL,
    fecha_salida          DATE NOT NULL,
    fecha_llegada         DATE NOT NULL,
    precio_base           NUMBER(10,2) NOT NULL,
    asientos_disponibles  NUMBER(4) NOT NULL,
    estado                VARCHAR2(15) DEFAULT 'PROGRAMADO' NOT NULL,

    CONSTRAINT pk_av_vuelos PRIMARY KEY (vuelo_id),
    CONSTRAINT fk_av_vue_aero FOREIGN KEY (aerolinea_id)
        REFERENCES av_aerolineas (aerolinea_id),
    CONSTRAINT fk_av_vue_origen FOREIGN KEY (aeropuerto_origen_id)
        REFERENCES av_aeropuertos (aeropuerto_id),
    CONSTRAINT fk_av_vue_destino FOREIGN KEY (aeropuerto_destino_id)
        REFERENCES av_aeropuertos (aeropuerto_id),
    CONSTRAINT uq_av_vue_num_fecha UNIQUE (aerolinea_id, num_vuelo, fecha_salida),
    CONSTRAINT ck_av_vue_ruta CHECK (aeropuerto_origen_id <> aeropuerto_destino_id),
    CONSTRAINT ck_av_vue_fechas CHECK (fecha_llegada > fecha_salida),
    CONSTRAINT ck_av_vue_precio CHECK (precio_base >= 0),
    CONSTRAINT ck_av_vue_asientos CHECK (asientos_disponibles >= 0),
    CONSTRAINT ck_av_vue_estado CHECK (estado IN
        ('PROGRAMADO', 'EN VUELO', 'COMPLETADO', 'CANCELADO'))
);

-- Transporte terrestre (bus, tren, van entre ciudades)
CREATE TABLE av_transportes_terrestres (
    transporte_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipo               VARCHAR2(10) NOT NULL,
    empresa            VARCHAR2(60) NOT NULL,
    ciudad_origen_id   NUMBER NOT NULL,
    ciudad_destino_id  NUMBER NOT NULL,
    fecha_salida       DATE NOT NULL,
    fecha_llegada      DATE NOT NULL,
    precio             NUMBER(10,2) NOT NULL,
    cupos_disponibles  NUMBER(3) NOT NULL,
    estado             VARCHAR2(15) DEFAULT 'PROGRAMADO' NOT NULL,

    CONSTRAINT pk_av_transp PRIMARY KEY (transporte_id),
    CONSTRAINT fk_av_transp_origen FOREIGN KEY (ciudad_origen_id)
        REFERENCES av_ciudades (ciudad_id),
    CONSTRAINT fk_av_transp_destino FOREIGN KEY (ciudad_destino_id)
        REFERENCES av_ciudades (ciudad_id),
    CONSTRAINT ck_av_transp_tipo CHECK (tipo IN ('BUS', 'TREN', 'VAN')),
    CONSTRAINT ck_av_transp_ruta CHECK (ciudad_origen_id <> ciudad_destino_id),
    CONSTRAINT ck_av_transp_fechas CHECK (fecha_llegada > fecha_salida),
    CONSTRAINT ck_av_transp_precio CHECK (precio >= 0),
    CONSTRAINT ck_av_transp_cupos CHECK (cupos_disponibles >= 0),
    CONSTRAINT ck_av_transp_estado CHECK (estado IN
        ('PROGRAMADO', 'EN RUTA', 'COMPLETADO', 'CANCELADO'))
);

------------------------------------------------------------ RESERVAS ------------------------------------------------------------
-- Reserva: cabecera del viaje completo (un cliente titular)
CREATE TABLE av_reservas (
    reserva_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    cliente_id         NUMBER NOT NULL,     -- titular / pagador
    fecha_reserva      DATE DEFAULT SYSDATE NOT NULL,
    fecha_inicio_viaje DATE NOT NULL,
    fecha_fin_viaje    DATE NOT NULL,
    monto_total        NUMBER(12,2) NOT NULL,
    estado             VARCHAR2(20) DEFAULT 'ACTIVA' NOT NULL,

    CONSTRAINT pk_av_reservas PRIMARY KEY (reserva_id),
    CONSTRAINT fk_av_res_cli FOREIGN KEY (cliente_id)
        REFERENCES av_clientes (cliente_id),
    CONSTRAINT ck_av_res_fechas CHECK (fecha_fin_viaje > fecha_inicio_viaje),
    CONSTRAINT ck_av_res_inicio CHECK (fecha_inicio_viaje >= fecha_reserva),
    CONSTRAINT ck_av_res_monto CHECK (monto_total >= 0),
    CONSTRAINT ck_av_res_estado CHECK (estado IN
        ('ACTIVA', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA', 'NO SHOW'))
);

-- Pasajeros de la reserva: REGLA CLAVE

CREATE TABLE av_reserva_pasajeros (
    reserva_id    NUMBER NOT NULL,
    num_pasajero  NUMBER(1) NOT NULL,
    cliente_id    NUMBER NOT NULL,

    CONSTRAINT pk_av_res_pas PRIMARY KEY (reserva_id, num_pasajero),
    CONSTRAINT fk_av_res_pas_res FOREIGN KEY (reserva_id)
        REFERENCES av_reservas (reserva_id),
    CONSTRAINT fk_av_res_pas_cli FOREIGN KEY (cliente_id)
        REFERENCES av_clientes (cliente_id),
    CONSTRAINT uq_av_res_pas_cli UNIQUE (reserva_id, cliente_id),  -- no duplicar
    CONSTRAINT ck_av_res_pas_num CHECK (num_pasajero IN (1, 2))
);

-- Vuelos incluidos en la reserva (una reserva puede tener 0..N vuelos: ida, regreso, escalas)
CREATE TABLE av_reserva_vuelos (
    detalle_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    reserva_id       NUMBER NOT NULL,   
    vuelo_id         NUMBER NOT NULL,
    precio_aplicado  NUMBER(10,2) NOT NULL,
    estado           VARCHAR2(15) DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_av_res_vue PRIMARY KEY (detalle_id),
    CONSTRAINT fk_av_resvue_res FOREIGN KEY (reserva_id)
        REFERENCES av_reservas (reserva_id),
    CONSTRAINT fk_av_resvue_vue FOREIGN KEY (vuelo_id)
        REFERENCES av_vuelos (vuelo_id),
    CONSTRAINT uq_av_resvue UNIQUE (reserva_id, vuelo_id),
    CONSTRAINT ck_av_resvue_precio CHECK (precio_aplicado >= 0),
    CONSTRAINT ck_av_resvue_estado CHECK (estado IN ('ACTIVO', 'CANCELADO'))
);

-- Hospedajes incluidos en la reserva
CREATE TABLE av_reserva_hospedajes (
    detalle_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    reserva_id      NUMBER NOT NULL,
    habitacion_id   NUMBER NOT NULL,
    fecha_checkin   DATE NOT NULL,
    fecha_checkout  DATE NOT NULL,
    num_noches      NUMBER(3) NOT NULL,
    precio_total    NUMBER(10,2) NOT NULL,
    estado          VARCHAR2(15) DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_av_res_hos PRIMARY KEY (detalle_id),
    CONSTRAINT fk_av_reshos_res FOREIGN KEY (reserva_id)
        REFERENCES av_reservas (reserva_id),
    CONSTRAINT fk_av_reshos_hab FOREIGN KEY (habitacion_id)
        REFERENCES av_habitaciones (habitacion_id),
    CONSTRAINT ck_av_reshos_fechas CHECK (fecha_checkout > fecha_checkin),
    CONSTRAINT ck_av_reshos_noches CHECK (num_noches > 0),
    CONSTRAINT ck_av_reshos_precio CHECK (precio_total >= 0),
    CONSTRAINT ck_av_reshos_estado CHECK (estado IN ('ACTIVO', 'CANCELADO'))
);

-- Transportes terrestres incluidos en la reserva
CREATE TABLE av_reserva_transportes (
    detalle_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    reserva_id       NUMBER NOT NULL,
    transporte_id    NUMBER NOT NULL,
    precio_aplicado  NUMBER(10,2) NOT NULL,
    estado           VARCHAR2(15) DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_av_res_tra PRIMARY KEY (detalle_id),
    CONSTRAINT fk_av_restra_res FOREIGN KEY (reserva_id)
        REFERENCES av_reservas (reserva_id),
    CONSTRAINT fk_av_restra_tra FOREIGN KEY (transporte_id)
        REFERENCES av_transportes_terrestres (transporte_id),
    CONSTRAINT uq_av_restra UNIQUE (reserva_id, transporte_id),
    CONSTRAINT ck_av_restra_precio CHECK (precio_aplicado >= 0),
    CONSTRAINT ck_av_restra_estado CHECK (estado IN ('ACTIVO', 'CANCELADO'))
);

--------------------------------------------------------------- FINANZAS ---------------------------------------------------------------
CREATE TABLE av_pagos (
    pago_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    reserva_id  NUMBER NOT NULL,
    fecha_pago  DATE DEFAULT SYSDATE NOT NULL,
    monto_pago  NUMBER(12,2) NOT NULL,
    canal_pago  VARCHAR2(30) DEFAULT 'TARJETA DE CREDITO' NOT NULL,
    referencia  VARCHAR2(50),

    CONSTRAINT pk_av_pagos PRIMARY KEY (pago_id),
    CONSTRAINT fk_av_pago_res FOREIGN KEY (reserva_id)
        REFERENCES av_reservas (reserva_id),
    CONSTRAINT ck_av_pago_monto CHECK (monto_pago >= 0),
    CONSTRAINT ck_av_pago_canal CHECK (canal_pago IN
        ('TARJETA DE CREDITO', 'TARJETA DEBITO', 'PSE', 'TRANSFERENCIA', 'EFECTIVO'))
);

CREATE TABLE av_notas_cancelacion (
    nota_id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    reserva_id        NUMBER NOT NULL,
    fecha_nota        DATE DEFAULT SYSDATE NOT NULL,
    monto_devolucion  NUMBER(12,2) NOT NULL,
    motivo            VARCHAR2(60) DEFAULT 'CANCELACION VOLUNTARIA' NOT NULL,

    CONSTRAINT pk_av_notas PRIMARY KEY (nota_id),
    CONSTRAINT fk_av_nota_res FOREIGN KEY (reserva_id)
        REFERENCES av_reservas (reserva_id),
    CONSTRAINT ck_av_nota_monto CHECK (monto_devolucion >= 0)
);


commit;

-------------------------------------------------------------------------------------------------------------------------

----------------------------------------------- INSERTS ------------------------------------------------------------

-- =========================================================
-- 1. PAÍSES (10 países, portafolio de la agencia)
-- =========================================================
INSERT INTO av_paises (pais_id, codigo_iso, nombre, continente) VALUES (1,  'COL', 'Colombia',       'AMERICA');
INSERT INTO av_paises (pais_id, codigo_iso, nombre, continente) VALUES (2,  'MEX', 'México',         'AMERICA');
INSERT INTO av_paises (pais_id, codigo_iso, nombre, continente) VALUES (3,  'USA', 'Estados Unidos', 'AMERICA');
INSERT INTO av_paises (pais_id, codigo_iso, nombre, continente) VALUES (4,  'ARG', 'Argentina',      'AMERICA');
INSERT INTO av_paises (pais_id, codigo_iso, nombre, continente) VALUES (5,  'ESP', 'España',         'EUROPA');
INSERT INTO av_paises (pais_id, codigo_iso, nombre, continente) VALUES (6,  'FRA', 'Francia',        'EUROPA');
INSERT INTO av_paises (pais_id, codigo_iso, nombre, continente) VALUES (7,  'ITA', 'Italia',         'EUROPA');
INSERT INTO av_paises (pais_id, codigo_iso, nombre, continente) VALUES (8,  'BRA', 'Brasil',         'AMERICA');
INSERT INTO av_paises (pais_id, codigo_iso, nombre, continente) VALUES (9,  'PER', 'Perú',           'AMERICA');
INSERT INTO av_paises (pais_id, codigo_iso, nombre, continente) VALUES (10, 'CHL', 'Chile',          'AMERICA');

-- =========================================================
-- 2. CIUDADES (18 ciudades distribuidas en los 10 países)
-- =========================================================
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (1,  1,  'Medellín');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (2,  1,  'Bogotá');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (3,  1,  'Cartagena');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (4,  2,  'Ciudad de México');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (5,  2,  'Cancún');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (6,  3,  'Miami');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (7,  3,  'Nueva York');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (8,  4,  'Buenos Aires');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (9,  5,  'Madrid');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (10, 5,  'Barcelona');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (11, 6,  'París');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (12, 7,  'Roma');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (13, 7,  'Milán');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (14, 8,  'Río de Janeiro');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (15, 8,  'São Paulo');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (16, 9,  'Lima');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (17, 9,  'Cusco');
INSERT INTO av_ciudades (ciudad_id, pais_id, nombre) VALUES (18, 10, 'Santiago');

-- =========================================================
-- 3. AEROLÍNEAS (8 aerolíneas con su país de origen)
-- =========================================================
INSERT INTO av_aerolineas (aerolinea_id, codigo_iata, nombre,              pais_id) VALUES (1, 'AV', 'Avianca',            1);
INSERT INTO av_aerolineas (aerolinea_id, codigo_iata, nombre,              pais_id) VALUES (2, 'LA', 'LATAM Airlines',     10);
INSERT INTO av_aerolineas (aerolinea_id, codigo_iata, nombre,              pais_id) VALUES (3, 'AM', 'Aeroméxico',         2);
INSERT INTO av_aerolineas (aerolinea_id, codigo_iata, nombre,              pais_id) VALUES (4, 'AA', 'American Airlines',  3);
INSERT INTO av_aerolineas (aerolinea_id, codigo_iata, nombre,              pais_id) VALUES (5, 'IB', 'Iberia',             5);
INSERT INTO av_aerolineas (aerolinea_id, codigo_iata, nombre,              pais_id) VALUES (6, 'AF', 'Air France',         6);
INSERT INTO av_aerolineas (aerolinea_id, codigo_iata, nombre,              pais_id) VALUES (7, 'AZ', 'ITA Airways',        7);
INSERT INTO av_aerolineas (aerolinea_id, codigo_iata, nombre,              pais_id) VALUES (8, 'G3', 'GOL Linhas Aéreas',  8);

-- =========================================================
-- 4. AEROPUERTOS (1 por ciudad principal, 18 en total)
-- =========================================================
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (1,  'MDE', 'José María Córdova',                  1);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (2,  'BOG', 'El Dorado',                           2);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (3,  'CTG', 'Rafael Núñez',                        3);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (4,  'MEX', 'Benito Juárez',                       4);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (5,  'CUN', 'Cancún Internacional',                5);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (6,  'MIA', 'Miami Internacional',                 6);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (7,  'JFK', 'John F. Kennedy',                     7);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (8,  'EZE', 'Ministro Pistarini Ezeiza',           8);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (9,  'MAD', 'Adolfo Suárez Madrid-Barajas',        9);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (10, 'BCN', 'Josep Tarradellas Barcelona-El Prat', 10);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (11, 'CDG', 'Charles de Gaulle',                   11);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (12, 'FCO', 'Leonardo da Vinci Fiumicino',         12);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (13, 'MXP', 'Malpensa',                            13);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (14, 'GIG', 'Galeão',                              14);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (15, 'GRU', 'Guarulhos',                           15);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (16, 'LIM', 'Jorge Chávez Internacional',          16);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (17, 'CUZ', 'Alejandro Velasco Astete',            17);
INSERT INTO av_aeropuertos (aeropuerto_id, codigo_iata, nombre,                              ciudad_id) VALUES (18, 'SCL', 'Arturo Merino Benítez',               18);

-- =========================================================
-- 5. HOTELES (10 hoteles, uno o dos por ciudad clave)
-- =========================================================
INSERT INTO av_hoteles (hotel_id, nombre,                              ciudad_id, direccion,                              estrellas) VALUES (1,  'The Charlee Lifestyle Hotel',        1,  'Cra. 35 #7-62, El Poblado',            5);
INSERT INTO av_hoteles (hotel_id, nombre,                              ciudad_id, direccion,                              estrellas) VALUES (2,  'Hotel Tequendama',                   2,  'Cra. 10 #26-21',                       4);
INSERT INTO av_hoteles (hotel_id, nombre,                              ciudad_id, direccion,                              estrellas) VALUES (3,  'Hotel Las Américas Casa de Playa',   3,  'Anillo Vial, Sector Cielo Mar',        5);
INSERT INTO av_hoteles (hotel_id, nombre,                              ciudad_id, direccion,                              estrellas) VALUES (4,  'Hotel Camino Real Polanco',          4,  'Mariano Escobedo 700, Polanco',        5);
INSERT INTO av_hoteles (hotel_id, nombre,                              ciudad_id, direccion,                              estrellas) VALUES (5,  'Hotel Riu Cancún',                   5,  'Blvd. Kukulcán Km 11.5',               5);
INSERT INTO av_hoteles (hotel_id, nombre,                              ciudad_id, direccion,                              estrellas) VALUES (6,  'Fontainebleau Miami Beach',          6,  '4441 Collins Avenue',                  5);
INSERT INTO av_hoteles (hotel_id, nombre,                              ciudad_id, direccion,                              estrellas) VALUES (7,  'Hotel Riu Plaza España',             9,  'Plaza España 8',                       4);
INSERT INTO av_hoteles (hotel_id, nombre,                              ciudad_id, direccion,                              estrellas) VALUES (8,  'Hotel Arts Barcelona',               10, 'Carrer de la Marina 19-21',            5);
INSERT INTO av_hoteles (hotel_id, nombre,                              ciudad_id, direccion,                              estrellas) VALUES (9,  'Hotel Le Meurice',                   11, '228 Rue de Rivoli',                    5);
INSERT INTO av_hoteles (hotel_id, nombre,                              ciudad_id, direccion,                              estrellas) VALUES (10, 'Hotel Hassler Roma',                 12, 'Piazza della Trinità dei Monti 6',     5);

-- =========================================================
-- 6. HABITACIONES (3 por hotel = 30 habitaciones)
--    Precio en COP por noche
-- =========================================================
-- Hotel 1: The Charlee (Medellín)
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (1,  1, '101', 'SENCILLA', 1, 450000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (2,  1, '201', 'DOBLE',    2, 650000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (3,  1, '301', 'SUITE',    4, 1200000);
-- Hotel 2: Tequendama (Bogotá)
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (4,  2, '101', 'SENCILLA', 1, 320000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (5,  2, '205', 'DOBLE',    2, 480000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (6,  2, '405', 'FAMILIAR', 4, 750000);
-- Hotel 3: Las Américas (Cartagena)
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (7,  3, '110', 'SENCILLA', 1, 520000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (8,  3, '215', 'DOBLE',    2, 780000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (9,  3, '315', 'SUITE',    4, 1500000);
-- Hotel 4: Camino Real Polanco (CDMX)
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (10, 4, '102', 'SENCILLA', 1, 850000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (11, 4, '208', 'DOBLE',    2, 1200000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (12, 4, '410', 'SUITE',    4, 2200000);
-- Hotel 5: Riu Cancún
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (13, 5, '120', 'SENCILLA', 1, 950000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (14, 5, '225', 'DOBLE',    2, 1400000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (15, 5, '502', 'FAMILIAR', 4, 1800000);
-- Hotel 6: Fontainebleau (Miami)
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (16, 6, '305', 'SENCILLA',  1, 1400000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (17, 6, '410', 'DOBLE',     2, 1900000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (18, 6, '1205','SUITE',     4, 3500000);
-- Hotel 7: Riu Plaza España (Madrid)
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (19, 7, '215', 'SENCILLA', 1, 780000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (20, 7, '318', 'DOBLE',    2, 1100000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (21, 7, '520', 'FAMILIAR', 4, 1700000);
-- Hotel 8: Arts Barcelona
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (22, 8, '408', 'SENCILLA', 1, 1300000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (23, 8, '612', 'DOBLE',    2, 1800000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (24, 8, '2010','SUITE',    4, 3800000);
-- Hotel 9: Le Meurice (París)
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (25, 9, '110', 'SENCILLA', 1, 2200000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (26, 9, '305', 'DOBLE',    2, 3000000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (27, 9, '501', 'SUITE',    4, 6500000);
-- Hotel 10: Hassler Roma
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (28, 10,'220', 'SENCILLA', 1, 1500000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (29, 10,'415', 'DOBLE',    2, 2100000);
INSERT INTO av_habitaciones (habitacion_id, hotel_id, num_habitacion, tipo,       capacidad, precio_noche) VALUES (30, 10,'605', 'SUITE',    4, 4500000);

-- =========================================================
-- 7. VUELOS (14 vuelos en distintas rutas, junio-agosto 2026)
--    Precio base en COP
-- =========================================================
-- Vuelos domésticos Colombia
INSERT INTO av_vuelos (vuelo_id, aerolinea_id, num_vuelo, aeropuerto_origen_id, aeropuerto_destino_id, fecha_salida, fecha_llegada, precio_base, asientos_disponibles)
VALUES (1, 1, 'AV245', 1, 2, TO_DATE('2026-06-15 06:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-06-15 07:00','YYYY-MM-DD HH24:MI'), 380000, 80);

INSERT INTO av_vuelos (vuelo_id, aerolinea_id, num_vuelo, aeropuerto_origen_id, aeropuerto_destino_id, fecha_salida, fecha_llegada, precio_base, asientos_disponibles)
VALUES (2, 1, 'AV248', 2, 1, TO_DATE('2026-06-15 18:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-06-15 19:00','YYYY-MM-DD HH24:MI'), 380000, 75);

INSERT INTO av_vuelos (vuelo_id, aerolinea_id, num_vuelo, aeropuerto_origen_id, aeropuerto_destino_id, fecha_salida, fecha_llegada, precio_base, asientos_disponibles)
VALUES (3, 1, 'AV320', 2, 3, TO_DATE('2026-06-20 09:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-06-20 10:30','YYYY-MM-DD HH24:MI'), 450000, 70);

-- Vuelos internacionales desde/hacia Colombia
INSERT INTO av_vuelos (vuelo_id, aerolinea_id, num_vuelo, aeropuerto_origen_id, aeropuerto_destino_id, fecha_salida, fecha_llegada, precio_base, asientos_disponibles)
VALUES (4, 1, 'AV520', 2, 6, TO_DATE('2026-07-01 23:30','YYYY-MM-DD HH24:MI'), TO_DATE('2026-07-02 04:00','YYYY-MM-DD HH24:MI'), 2200000, 150);

INSERT INTO av_vuelos (vuelo_id, aerolinea_id, num_vuelo, aeropuerto_origen_id, aeropuerto_destino_id, fecha_salida, fecha_llegada, precio_base, asientos_disponibles)
VALUES (5, 4, 'AA982', 6, 2, TO_DATE('2026-07-10 08:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-07-10 12:30','YYYY-MM-DD HH24:MI'), 2300000, 140);

INSERT INTO av_vuelos (vuelo_id, aerolinea_id, num_vuelo, aeropuerto_origen_id, aeropuerto_destino_id, fecha_salida, fecha_llegada, precio_base, asientos_disponibles)
VALUES (6, 1, 'AV010', 2, 9, TO_DATE('2026-07-05 17:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-07-06 09:30','YYYY-MM-DD HH24:MI'), 4800000, 200);

INSERT INTO av_vuelos (vuelo_id, aerolinea_id, num_vuelo, aeropuerto_origen_id, aeropuerto_destino_id, fecha_salida, fecha_llegada, precio_base, asientos_disponibles)
VALUES (7, 5, 'IB6586', 9, 2, TO_DATE('2026-07-25 12:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-07-25 17:30','YYYY-MM-DD HH24:MI'), 5100000, 180);

INSERT INTO av_vuelos (vuelo_id, aerolinea_id, num_vuelo, aeropuerto_origen_id, aeropuerto_destino_id, fecha_salida, fecha_llegada, precio_base, asientos_disponibles)
VALUES (8, 3, 'AM6', 2, 4, TO_DATE('2026-06-25 14:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-06-25 18:30','YYYY-MM-DD HH24:MI'), 1900000, 130);

INSERT INTO av_vuelos (vuelo_id, aerolinea_id, num_vuelo, aeropuerto_origen_id, aeropuerto_destino_id, fecha_salida, fecha_llegada, precio_base, asientos_disponibles)
VALUES (9, 2, 'LA704', 2, 16, TO_DATE('2026-08-10 07:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-08-10 10:00','YYYY-MM-DD HH24:MI'), 1600000, 120);

-- Vuelos entre destinos turísticos
INSERT INTO av_vuelos (vuelo_id, aerolinea_id, num_vuelo, aeropuerto_origen_id, aeropuerto_destino_id, fecha_salida, fecha_llegada, precio_base, asientos_disponibles)
VALUES (10, 2, 'LA2476', 16, 17, TO_DATE('2026-08-12 06:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-08-12 07:30','YYYY-MM-DD HH24:MI'), 480000, 90);

INSERT INTO av_vuelos (vuelo_id, aerolinea_id, num_vuelo, aeropuerto_origen_id, aeropuerto_destino_id, fecha_salida, fecha_llegada, precio_base, asientos_disponibles)
VALUES (11, 5, 'IB3404', 9, 10, TO_DATE('2026-07-12 10:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-07-12 11:30','YYYY-MM-DD HH24:MI'), 380000, 100);

INSERT INTO av_vuelos (vuelo_id, aerolinea_id, num_vuelo, aeropuerto_origen_id, aeropuerto_destino_id, fecha_salida, fecha_llegada, precio_base, asientos_disponibles)
VALUES (12, 6, 'AF1304', 11, 9, TO_DATE('2026-07-15 08:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-07-15 10:00','YYYY-MM-DD HH24:MI'), 550000, 90);

INSERT INTO av_vuelos (vuelo_id, aerolinea_id, num_vuelo, aeropuerto_origen_id, aeropuerto_destino_id, fecha_salida, fecha_llegada, precio_base, asientos_disponibles)
VALUES (13, 7, 'AZ318', 12, 11, TO_DATE('2026-07-18 14:30','YYYY-MM-DD HH24:MI'), TO_DATE('2026-07-18 16:30','YYYY-MM-DD HH24:MI'), 580000, 110);

INSERT INTO av_vuelos (vuelo_id, aerolinea_id, num_vuelo, aeropuerto_origen_id, aeropuerto_destino_id, fecha_salida, fecha_llegada, precio_base, asientos_disponibles)
VALUES (14, 8, 'G31845', 15, 14, TO_DATE('2026-08-05 11:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-08-05 12:00','YYYY-MM-DD HH24:MI'), 320000, 100);

-- =========================================================
-- 8. TRANSPORTES TERRESTRES (6 rutas en bus o tren)
-- =========================================================
INSERT INTO av_transportes_terrestres (transporte_id, tipo,  empresa,                    ciudad_origen_id, ciudad_destino_id, fecha_salida, fecha_llegada, precio, cupos_disponibles)
VALUES (1, 'BUS',  'Expreso Bolivariano',         1,  2,  TO_DATE('2026-06-15 06:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-06-15 16:00','YYYY-MM-DD HH24:MI'), 180000, 40);

INSERT INTO av_transportes_terrestres (transporte_id, tipo,  empresa,                    ciudad_origen_id, ciudad_destino_id, fecha_salida, fecha_llegada, precio, cupos_disponibles)
VALUES (2, 'BUS',  'Berlinas del Fonce',          2,  3,  TO_DATE('2026-06-22 18:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-06-23 10:00','YYYY-MM-DD HH24:MI'), 220000, 35);

INSERT INTO av_transportes_terrestres (transporte_id, tipo,  empresa,                    ciudad_origen_id, ciudad_destino_id, fecha_salida, fecha_llegada, precio, cupos_disponibles)
VALUES (3, 'TREN', 'Renfe AVE',                   9,  10, TO_DATE('2026-07-13 09:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-07-13 11:30','YYYY-MM-DD HH24:MI'), 320000, 250);

INSERT INTO av_transportes_terrestres (transporte_id, tipo,  empresa,                    ciudad_origen_id, ciudad_destino_id, fecha_salida, fecha_llegada, precio, cupos_disponibles)
VALUES (4, 'TREN', 'Trenitalia Frecciarossa',     12, 13, TO_DATE('2026-07-20 10:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-07-20 13:00','YYYY-MM-DD HH24:MI'), 380000, 200);

INSERT INTO av_transportes_terrestres (transporte_id, tipo,  empresa,                    ciudad_origen_id, ciudad_destino_id, fecha_salida, fecha_llegada, precio, cupos_disponibles)
VALUES (5, 'BUS',  'Cruz del Sur',                16, 17, TO_DATE('2026-08-12 20:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-08-13 16:00','YYYY-MM-DD HH24:MI'), 250000, 45);

INSERT INTO av_transportes_terrestres (transporte_id, tipo,  empresa,                    ciudad_origen_id, ciudad_destino_id, fecha_salida, fecha_llegada, precio, cupos_disponibles)
VALUES (6, 'BUS',  'Expresso Brasileiro',         15, 14, TO_DATE('2026-08-06 09:00','YYYY-MM-DD HH24:MI'), TO_DATE('2026-08-06 15:00','YYYY-MM-DD HH24:MI'), 190000, 50);

COMMIT;


SELECT table_name
FROM user_tables;
select * from av_transportes_terrestres
;